version: '3'

services:
  my:
    build: .
    container_name: arch-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./conf:/etc/openvpn/client
    stdin_open: true
    tty: true
