#!/bin/sh

if [ -f "$1" ]; then
  filename="$1"
elif [ -f "/data/$CONFIG" ]; then
  filename="/data/$CONFIG"
else
  filename="$(find /data/ -type f -name "*.conf" -o -name "*.ovpn" | shuf -n 1)"
fi

credentials='/data/credentials.txt'

if [ -z "$filename" ]; then
  echo "Config OpenVPN dir is empty: $filename"
  exit 0
fi

echo "Staring VPN with: $filename"
params=""
if [ -f "$credentials" ]; then
    params="--auth-user-pass $credentials"
fi

set -x
openvpn --config "$filename" $params
